#! /bin/bash
# Wed Feb 12 10:50:50 UTC 2020; HH-RIPE; Henrik Harms
# vim: set nohlsearch ts=4 sw=4 :
# saves ipsets separated by names
# restore like this: cat /etc/ipsets/*.conf | /usr/sbin/ipset restore
#
# This file is part of ipblockd.
# Copyright: (c) 2020,2024 Henrik Harms
# https://github.com/digitalhippie0/ipblockd
#
# ipblockd is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free 
# Software Foundation, either version 3 of the License, or (at your option) 
# any later version.
#
# ipblockd is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with ipblockd. If not, see <https://www.gnu.org/licenses/>. 

IPSET='/usr/sbin/ipset'
BASE='/etc/ipsets'
SUFFIX='conf'

mkdir -p ${BASE}

for SET in $( ${IPSET} list -t | grep "Name: " | cut -d ' ' -f2); do
	${IPSET} save ${SET} > ${BASE}/${SET}.${SUFFIX}
done
