#! /bin/bash
# vim: set ts=4 sw=4 :
#
# This file is part of ipblockd.
# Copyright: (c) 2024 Henrik Harms
# https://github.com/digitalhippie0/ipblockd
#
# ipblockd is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free 
# Software Foundation, either version 3 of the License, or (at your option) 
# any later version.
#
# ipblockd is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with ipblockd. If not, see <https://www.gnu.org/licenses/>. 

lsipset () 
{ 
	export IPSET_BASE=${IPSET_BASE=ipblockd}
	if [ "${1}" == "" ]; then
		export NUM=25;
	else
		export NUM=${1};
	fi;
	watch -n5 '
		echo "top ${NUM} networks:"
		ipset list ${IPSET_BASE}-nets | grep "packets" | grep -v "packets 0" | sort -r -n -k5 | head -${NUM}
		echo 
		echo "top ${NUM} individual hosts:"
		ipset list ${IPSET_BASE} | grep "packets" | grep -v "packets 0" | sort -r -n -k5 | head -${NUM}
	';
	unset NUM
	unset IPSET_BASE
}
